- id: leave_home
  alias: Leave Home
  trigger:
    platform: zone
    entity_id: device_tracker.ben
    zone: zone.home
    event: leave
  action:
  - service: notify.pushbullet
    data:
      message: Ben left home
- id: arrive_home
  alias: Arrive Home
  trigger:
    platform: zone
    entity_id: device_tracker.ben
    zone: zone.home
    event: enter
  action:
  - service: notify.pushbullet
    data:
      message: Ben arrived home
- id: britt_left_home
  alias: Britt Left Home
  trigger:
    platform: zone
    entity_id: device_tracker.britt
    zone: zone.home
    event: leave
  action:
  - service: notify.pushbullet
    data:
      message: Britt left home
- id: britt_arrived_home
  alias: Britt Arrived Home
  trigger:
    platform: zone
    entity_id: device_tracker.britt
    zone: zone.home
    event: enter
  action:
  - service: notify.pushbullet
    data:
      message: Britt arrived home
- id: leave_work
  alias: Leave Work
  trigger:
    platform: zone
    entity_id: device_tracker.ben
    zone: zone.work
    event: leave
  action:
  - service: notify.pushbullet
    data:
      message: Ben left work
- id: arrive_at_work
  alias: Arrive at Work
  trigger:
    platform: zone
    entity_id: device_tracker.ben
    zone: zone.work
    event: enter
  action:
  - service: notify.pushbullet
    data:
      message: Ben arrived at work
- id: enable_todays_alarm
  alias: Enable todays alarm
  trigger:
    platform: time
    at: '9:00:00'
  condition:
    condition: state
    entity_id: input_boolean.alarm_lights
    state: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.alarm_lights_today
- id: disable_todays_alarm
  alias: Disable todays alarm
  trigger:
    platform: time
    at: '9:00:00'
  condition:
    condition: state
    entity_id: input_boolean.alarm_lights
    state: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.alarm_lights_today
- id: garage_open
  alias: Garage Open
  trigger:
  - entity_id: cover.west_garage_door, cover.east_garage_door
    for:
      minutes: 5
    platform: state
    to: open
  condition:
  - condition: state
    entity_id: group.our_devices
    state: Away
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes["friendly_name"] }} has been {{ trigger.to_state.state
        }} for {{ trigger.for }}'
    service: notify.pushbullet
- id: garage_open_long_time
  alias: Garage Open for a long time
  trigger:
  - entity_id: cover.west_garage_door, cover.east_garage_door
    for:
      hours: 1
    platform: state
    to: open
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes["friendly_name"] }} has been {{ trigger.to_state.state
        }} for {{ trigger.for }}'
    service: notify.pushbullet
- id: arrive_home_living_room_lights
  alias: Arrive Home Living Room Lights
  trigger:
    platform: state
    entity_id: group.our_devices
    from: not_home
    to: home
  condition:
    condition: sun
    after: sunset
    after_offset: '-2:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_switch
- id: britt_walkup_music
  alias: Britt Walkup Music
  trigger:
    platform: state
    entity_id: device_tracker.britt
    from: not_home
    to: home
  action:
    service: script.walkup_music
    data:
      playlist: spotify:user:borigas:playlist:4SJmyv4yZ5NdpJ30XeJ3AA
- id: ben_walkup_music
  alias: Ben Walkup Music
  trigger:
    platform: state
    entity_id: device_tracker.ben
    from: not_home
    to: home
  action:
    service: script.walkup_music
    data:
      playlist: spotify:user:borigas:playlist:1jBiclFnkbb1kesKneqyL8
- action:
  - data:
      entity_id: group.lights
    service: homeassistant.turn_off
  alias: No One Home Lights Off
  condition: []
  id: '1523677900676'
  trigger:
  - entity_id: group.our_devices
    from: home
    platform: state
    to: not_home
- id: turn_off_phone_charger
  alias: Turn Off Phone Charger
  description: Turns off phone charger when it's battery is charged enough
  trigger:
  - platform: numeric_state
    entity_id: sensor.oneplus_6t_battery_level
    above: '80'
  condition:
  - type: is_plugged_in
    condition: device
    device_id: 9c73ef5fcee94f47ad5ae3b5f1eebe21
    entity_id: binary_sensor.oneplus_6t_is_charging
    domain: binary_sensor
  - condition: state
    entity_id: input_boolean.charger_automations
    state: 'On'
  action:
  - service: logbook.log
    data:
      name: Phone Charging Automatiion
      message: is turning off the charger to preserve battery health
      entity_id: switch.hank_electronics_ltd_hkzw_so01_smart_plug_switch
      domain: switch
  - service: switch.turn_off
    data: {}
    entity_id: switch.hank_electronics_ltd_hkzw_so01_smart_plug_switch
  mode: single
- id: turn_on_phone_charger
  alias: Turn On Phone Charger
  description: Turns on phone charger when it's battery needs to be charged
  trigger:
  - platform: numeric_state
    entity_id: sensor.oneplus_6t_battery_level
    below: '70'
  condition:
  - condition: state
    entity_id: input_boolean.charger_automations
    state: 'On'
  action:
  - service: logbook.log
    data:
      name: Phone Charging Automatiion
      message: is turning on the charger
      entity_id: switch.hank_electronics_ltd_hkzw_so01_smart_plug_switch
      domain: switch
  - service: switch.turn_on
    data: {}
    entity_id: switch.hank_electronics_ltd_hkzw_so01_smart_plug_switch
  mode: single
