homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 400
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize:
    light.bedroom_ceiling_level:
      friendly_name: Bedroom Ceiling
      icon: mdi:hotel
      emulated_hue_name: Bedroom
    switch.kitchen_ceiling_switch:
      friendly_name: Kitchen Ceiling
      icon: mdi:stove
    sensor.dark_sky_apparent_temperature:
      friendly_name: Temp
    sensor.dark_sky_daily_low_apparent_temperature:
      friendly_name: Low Temp
    sensor.dark_sky_daily_high_apparent_temperature:
      friendly_name: High Temp
    sensor.dark_sky_precip_probability:
      friendly_name: Precip %
    sensor.dark_sky_daily_max_precip_intensity:
      friendly_name: Precip Intensity
    sensor.dark_sky_summary:
      friendly_name: Now
    sensor.dark_sky_hourly_summary:
      friendly_name: Today
    sensor.dark_sky_daily_summary:
      friendly_name: This Week
    script.tv_center_volume_up:
      emulated_hue: true
    script.tv_center_volume_down:
      emulated_hue: true
    script.tv_center_volume_way_up:
      emulated_hue: true
    script.tv_center_volume_way_down:
      emulated_hue: true
    script.tv_center_mute:
      emulated_hue: true
    script.tv_center_power_down:
      emulated_hue: true
    script.tv_center_power_up:
      emulated_hue: true
    script.tv_sides_volume_up:
      emulated_hue: true
    script.tv_sides_volume_down:
      emulated_hue: true
    script.tv_sides_volume_way_up:
      emulated_hue: true
    script.tv_sides_volume_way_down:
      emulated_hue: true
    script.tv_sides_mute:
      emulated_hue: true
    script.tv_sides_power_down:
      emulated_hue: true
    script.tv_sides_power_up:
      emulated_hue: true
    script.tv_sides_off:
      emulated_hue: true
    script.tv_center_off:
      emulated_hue: true
    script.tv_living_room_off:
      emulated_hue: true
    script.tv_all_off:
      emulated_hue: true

script: !include scripts.yaml

automation: !include automations.yaml

zone:
  name: Work
  latitude: 40.813299
  longitude: -96.710486
  radius: 500
  icon: mdi:desktop-mac

zone 2:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

http:
  api_password: !secret http_password
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  server_port: 8123
  use_x_forwarded_for: true

emulated_hue:
  listen_port: 80
  exposed_domains:
    - switch
    - light
    - input_boolean
    - media_player
  
mqtt:
#  broker: m12.cloudmqtt.com
#  port: 14782
#  username: HomeAssistant
#  password: !secret mqtt_password
  broker: 127.0.0.1
  port: 1883


device_tracker:
  - platform: netgear
    host: 192.168.1.1
    username: admin
    password: !secret netgear_password
    port: 80
    track_new_devices: False
    interval_seconds: 60
    consider_home: 00:03:00

# Track the sun
#sun:

sensor:
  # Prediction of weather
  - platform: darksky
    api_key: !secret forecast_api_key
    update_interval: '01:00:00'
    monitored_conditions:
      - summary
      #- icon
      #- nearest_storm_distance
      #- nearest_storm_bearing
      #- precip_type
      - precip_intensity
      - precip_probability
      #- temperature
      - apparent_temperature
      #- dew_point
      - wind_speed
      - wind_bearing
      #- cloud_cover
      - humidity
      #- pressure
      #- visibility
      #- minutely_summary
      - hourly_summary
      - daily_summary
      #- temperature_max
      #- temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
  - platform: fastdotcom
    minute:
      - 5
      - 15
      - 25
      - 35
      - 45
      - 55
  - platform: mqtt
    state_topic: "home/garage/door/c0928600"
    name: "Britt's Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"
    value_template: '{{ value_json.Distance }}'
  - platform: mqtt
    state_topic: "home/garage/door/4413c000"
    name: "Ben's Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"
    value_template: '{{ value_json.Distance }}'

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend
conversation:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration panel
config:

# Discover some devices automatically
discovery:
  ignore:
    - netgear_router

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  client_id: 0f34338b-5247-45f3-b4a0-a09da4cabba1
  client_secret: !secret nest_secret

climate:
  platform: nest

remote:
  - platform: harmony
    name: LivingRoom
    host: 192.168.1.70

input_boolean:
  alarm_lights:
    name: Should Alarm Lights
    initial: on
    icon: mdi:alarm
  alarm_lights_today:
    name: Today's Alarm
    initial: off

switch:
  platform: dlink
  host: http://192.168.1.83
  username: !secret dlink_user
  password: !secret dlink_password
    
cover:
  - platform: mqtt
    name: "Britt's Garage Door"
    state_topic: "home/garage/door/c0928600"
    command_topic: "home/garage/door/c0928600/set"
    optimistic: false
    value_template: '{{ value_json.Status }}'
    payload_open: "open"
    payload_close: "close"
    state_open: "open"
    state_closed: "closed"
  - platform: mqtt
    name: "Ben's Garage Door"
    state_topic: "home/garage/door/4413c000"
    command_topic: "home/garage/door/4413c000/set"
    optimistic: false
    value_template: '{{ value_json.Status }}'
    payload_open: "open"
    payload_close: "close"
    state_open: "open"
    state_closed: "closed"

notify:
#  platform: html5
#  name: HTML5
#  gcm_api_key: !secret gcm_api_key
#  gcm_sender_id: !secret gcm_sender_id
  platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet


shell_command:
  update_hass: /home/pi/HomeAssistantConfig/update.sh
  pull_github: /home/pi/HomeAssistantConfig/git_pull.sh

group:
  default_view:
    view: yes
    entities:
      - updater.updater
      - device_tracker.ben
      - device_tracker.britt
      - group.garage
      - climate.hallway_nest
      - group.speedtest
      - group.media
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_precip_probability
      - light.bedroom_ceiling_level
      - switch.kitchen_ceiling_switch
      - switch.dlink_smart_plug_w215
  bedroom_alarm_lights:
    name: Bedroom Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_ceiling_level
  kitchen_lights:
    name: Kitchen Lights
    icon: mdi:lightbulb
    entities:
      - switch.kitchen_ceiling_switch
  speedtest:
    name: Speedtest
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.fastcom_download
  media:
    view: yes
    entities:
      - group.center_tv
      - group.side_tvs
      - media_player.basement_chromecast
  center_tv:
    name: Center TV
    entities:
      - script.tv_center_power_up
      - script.tv_center_power_down
      - script.tv_center_volume_up
      - script.tv_center_volume_down
      - script.tv_center_volume_way_up
      - script.tv_center_volume_way_down
      - script.tv_center_mute
      - media_player.center_chromecast
      - media_player.surround_chromecast
  side_tvs:
    name: Side TVs
    entities:
      - script.tv_sides_power_up
      - script.tv_sides_power_down
      - script.tv_sides_volume_up
      - script.tv_sides_volume_down
      - script.tv_sides_volume_way_up
      - script.tv_sides_volume_way_down
      - script.tv_sides_mute
      - media_player.left_chromecast
      - media_player.right_chromecast
  garage:
    name: Garage
    entities:
      - cover.bens_garage_door
      - cover.britts_garage_door
      - sensor.bens_garage_door_raw
      - sensor.britts_garage_door_raw
  Weather Summary:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
  Home Assistant:
    entities:
      - script.restart_hass
      - script.update_hass
      - script.pull_github
      - script.reload_automation
      - script.reload_groups
      - script.reload_core
      - input_boolean.alarm_lights
  Weather:
    view: yes
    entities:
      - group.weather_summary
  Admin:
    view: yes
    entities:
      - group.home_assistant
