homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 400
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize:
    light.bedroom_ceiling_level:
      friendly_name: Bedroom Ceiling
      icon: mdi:hotel
      emulated_hue_name: Bedroom
    switch.kitchen_ceiling_switch:
      friendly_name: Kitchen Ceiling
      icon: mdi:stove
    switch.living_room_switch:
      friendly_name: Living Room Lamps
      icon: mdi:readability
    sensor.dark_sky_apparent_temperature:
      friendly_name: Temp
    sensor.dark_sky_overnight_low_apparent_temperature_0d:
      friendly_name: Low Temp
    sensor.dark_sky_daytime_high_apparent_temperature_0d:
      friendly_name: High Temp
    sensor.dark_sky_precip_probability:
      friendly_name: Precip %
    sensor.dark_sky_daily_max_precip_intensity_0d:
      friendly_name: Precip Intensity
    sensor.dark_sky_summary:
      friendly_name: Now
    sensor.dark_sky_hourly_summary:
      friendly_name: Today
    sensor.dark_sky_daily_summary:
      friendly_name: This Week

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: legacy_api_password
      api_password: !secret http_password
    - type: homeassistant

system_health:

lovelace:
  mode: yaml

script: !include scripts.yaml

automation: !include automations.yaml

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

http:
  base_url: !secret base_url
  cors_allowed_origins: !secret base_url
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies: 192.168.1.20

emulated_hue:
  listen_port: 80
  exposed_domains:
    - switch
    - light
    - input_boolean
    - media_player
    - script

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - input_boolean
  entity_config:
    light.bedroom_ceiling_level:
      aliases:
        Bedroom
        Bedroom Ceiling


device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin
    password: !secret router_password

# Track the sun
#sun:

weather:
  - platform: darksky
    api_key: !secret forecast_api_key

sensor:
  - platform: uptime
    unit_of_measurement: hours
  # Prediction of weather
  - platform: darksky
    api_key: !secret forecast_api_key
    forecast:
      - 0
    monitored_conditions:
      - summary
      #- icon
      #- nearest_storm_distance
      #- nearest_storm_bearing
      #- precip_type
      - precip_intensity
      - precip_probability
      #- temperature
      - apparent_temperature
      #- dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      #- pressure
      #- visibility
      #- minutely_summary
      - hourly_summary
      - daily_summary
      #- temperature_high
      #- temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
  # - platform: speedtestdotnet
  #   monitored_conditions:
  #     - ping
  #     - download
  #     - upload
  #   scan_interval: '0:15'
  # - platform: fastdotcom
  #   scan_interval: '0:15'

# Allows you to issue voice commands from the frontend
conversation:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration panel
config:

# Discover some devices automatically
discovery:
  ignore:
    - netgear_router
    - igd
    - plex_mediaserver

# Enables support for tracking state changes over time.
recorder:
  db_url: mysql://hass:mariapassword@core-mariadb/homeassistant?charset=utf8
  include:
    domains:
      - automation
      - cover
      - light
      - switch
      - input_boolean
      - climate
    entities:
      - sensor.eastgaragesensor
      - sensor.westgaragesensor
      - sensor.east_garage_wifi
      - sensor.west_garage_wifi
      - sensor.east_garage_uptime
      - sensor.west_garage_uptime
      - device_tracker.ben
      - device_tracker.britt
      
history:

logbook:

# Checks for available updates
updater:

zwave:
  usb_path: /dev/ttyACM0
  #config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  client_id: 0f34338b-5247-45f3-b4a0-a09da4cabba1
  client_secret: !secret nest_secret

climate:
  platform: nest

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

input_boolean:
  alarm_lights:
    name: Should Alarm Lights
    icon: mdi:alarm-check
  alarm_lights_today:
    name: Today's Alarm
    icon: mdi:alarm-check

input_number:
  alarm_hour:
    name: Hour
    icon: mdi:timer
    min: 0
    max: 23
    step: 1
  alarm_minute:
    name: Minute
    icon: mdi:timer
    min: 0
    max: 55
    step: 5

tplink:
  discovery: true    

notify:
#  platform: html5
#  name: HTML5
#  gcm_api_key: !secret gcm_api_key
#  gcm_sender_id: !secret gcm_sender_id
  platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet

group:
  lights:
    name: Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_ceiling_level
      - switch.kitchen_ceiling_switch
      - switch.living_room_switch
  bedroom_alarm_lights:
    name: Bedroom Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_ceiling_level
  kitchen_lights:
    name: Kitchen Lights
    icon: mdi:lightbulb
    entities:
      - switch.kitchen_ceiling_switch
  speedtest:
    name: Speedtest
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.fastcom_download
  garage:
    name: Garage
    entities:
      - cover.west_garage_door
      - cover.east_garage_door
      - sensor.eastgaragesensor
      - sensor.westgaragesensor
  Weather Summary:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_overnight_low_apparent_temperature_0d
      - sensor.dark_sky_daytime_high_apparent_temperature_0d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_daily_max_precip_intensity_0d
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
  Alarms:
    entities:
      - input_boolean.alarm_lights
      - input_boolean.alarm_lights_today
      - input_number.alarm_hour
      - input_number.alarm_minute
  Automations:
    entities:
      - automation.arrive_home_living_room_lights
      - automation.ben_walkup_music
      - automation.britt_walkup_music
      - automation.disable_todays_alarm
      - automation.enable_todays_alarm
      - automation.garage_open
      - automation.garage_open_long_time
      - automation.no_one_home_lights_off
  our_devices:
    name: Our Devices
    entities:
      - device_tracker.ben
      - device_tracker.britt