homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 400
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize:
    light.bedroom_ceiling_level:
      friendly_name: Bedroom Ceiling
      icon: mdi:hotel
      emulated_hue_name: Bedroom
    switch.kitchen_ceiling_switch:
      friendly_name: Kitchen Ceiling
      icon: mdi:stove
    switch.living_room_switch:
      friendly_name: Living Room Lamps
      icon: mdi:readability
    sensor.dark_sky_apparent_temperature:
      friendly_name: Temp
    sensor.dark_sky_daily_low_apparent_temperature:
      friendly_name: Low Temp
    sensor.dark_sky_daily_high_apparent_temperature:
      friendly_name: High Temp
    sensor.dark_sky_precip_probability:
      friendly_name: Precip %
    sensor.dark_sky_daily_max_precip_intensity:
      friendly_name: Precip Intensity
    sensor.dark_sky_summary:
      friendly_name: Now
    sensor.dark_sky_hourly_summary:
      friendly_name: Today
    sensor.dark_sky_daily_summary:
      friendly_name: This Week
    cover.east_garage_door:
      friendly_name: Ben's Garage Door
    cover.west_garage_door:
      friendly_name: Britt's Garage Door

script: !include scripts.yaml

automation: !include automations.yaml

zone:
  name: Work
  latitude: 40.813299
  longitude: -96.710486
  radius: 500
  icon: mdi:desktop-mac

zone 2:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

http:
  api_password: !secret http_password
  base_url: !secret base_url
  cors_allowed_origins: !secret base_url
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  server_port: 8123
  use_x_forwarded_for: true

emulated_hue:
  listen_port: 80
  exposed_domains:
    - switch
    - light
    - input_boolean
    - media_player
    - script

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - input_boolean
  entity_config:
    light.bedroom_ceiling_level:
      aliases:
        Bedroom Ceiling
        Bedroom
    script.tv_sides_volume_up:
      name: Side Volume Up
      expose: true
    script.tv_sides_volume_down:
      name: Side Volume Down
      expose: true
    script.tv_sides_volume_way_up:
      name: Raise Side Volume
      expose: true
    script.tv_sides_volume_way_down:
      name: Lower Side Volume
      expose: true
    script.tv_sides_mute:
      name: Mute Sides
      expose: true
    script.tv_center_volume_up:
      name: Center Volume Up
      expose: true
    script.tv_center_volume_down:
      name: Center Volume Down
      expose: true
    script.tv_center_volume_way_up:
      name: Raise Center Volume
      expose: true
    script.tv_center_volume_way_down:
      name: Lower Center Volume
      expose: true
    script.tv_center_mute:
      name: Mute Center
      expose: true
    light.center_tv:
      aliases:
        - Center TV
        - Center Power Down
    light.side_tvs:
      aliases:
        - Side TVs
        - Sides Power Down
    light.living_room_tvs:
      aliases:
        - Living Room TVs
  
mqtt:
#  broker: m12.cloudmqtt.com
#  port: 14782
#  username: HomeAssistant
#  password: !secret mqtt_password
#  broker: 127.0.0.1
#  port: 1883
  broker: core-mosquitto
  discovery: true


device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin
    password: !secret router_password

# Track the sun
#sun:

sensor:
  - platform: uptime
    unit_of_measurement: hours
  # Prediction of weather
  - platform: darksky
    api_key: !secret forecast_api_key
    update_interval: '01:00:00'
    monitored_conditions:
      - summary
      #- icon
      #- nearest_storm_distance
      #- nearest_storm_bearing
      #- precip_type
      - precip_intensity
      - precip_probability
      #- temperature
      - apparent_temperature
      #- dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      #- pressure
      #- visibility
      #- minutely_summary
      - hourly_summary
      - daily_summary
      #- temperature_max
      #- temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
  - platform: fastdotcom
    minute:
      - 5
      - 15
      - 25
      - 35
      - 45
      - 55
  - platform: mqtt
    state_topic: "westgaragedoor/sensor/garagesensor/state"
    name: "Britt's Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"
  - platform: mqtt
    state_topic: "eastgaragedoor/sensor/garagesensor/state"
    name: "Ben's Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend
conversation:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration panel
config:

# Discover some devices automatically
discovery:
  ignore:
    - netgear_router

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

zwave:
  usb_path: /dev/ttyACM0
  #config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  client_id: 0f34338b-5247-45f3-b4a0-a09da4cabba1
  client_secret: !secret nest_secret

climate:
  platform: nest

remote:
  - platform: harmony
    name: LivingRoom
    host: 192.168.1.70
    activity: Center TV

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

input_boolean:
  alarm_lights:
    name: Should Alarm Lights
    icon: mdi:alarm-check
  alarm_lights_today:
    name: Today's Alarm
    icon: mdi:alarm-check

input_number:
  alarm_hour:
    name: Hour
    icon: mdi:timer
    min: 0
    max: 23
    step: 1
  alarm_minute:
    name: Minute
    icon: mdi:timer
    min: 0
    max: 55
    step: 5

switch:
  - platform: dlink
    host: http://192.168.1.83
    username: !secret dlink_user
    password: !secret dlink_password

light:
  - platform: template
    lights:
      center_tv:
        friendly_name: "Center TV"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.tv_center_power_up
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.tv_center_off
      side_tvs:
        friendly_name: "Side TVs"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.tv_sides_power_up
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.tv_sides_off
      living_room_tvs:
        friendly_name: "Living Room TVs"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.tv_center_power_up
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.living_room_off

notify:
#  platform: html5
#  name: HTML5
#  gcm_api_key: !secret gcm_api_key
#  gcm_sender_id: !secret gcm_sender_id
  platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet

group:
  default_view:
    name: Home
    view: yes
    entities:
      - updater.updater
      - device_tracker.ben
      - device_tracker.britt
      - group.garage
      - climate.hallway_nest
      - group.speedtest
      - group.media
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_precip_probability
      - group.lights
      - light.bedroom_ceiling_level
      - switch.dlink_smart_plug_w215
  lights:
    name: Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_ceiling_level
      - switch.kitchen_ceiling_switch
      - switch.living_room_switch
  bedroom_alarm_lights:
    name: Bedroom Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_ceiling_level
  kitchen_lights:
    name: Kitchen Lights
    icon: mdi:lightbulb
    entities:
      - switch.kitchen_ceiling_switch
  speedtest:
    name: Speedtest
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.fastcom_download
  media:
    view: yes
    entities:
      - group.center_tv
      - group.side_tvs
      - media_player.basement_chromecast
      - media_player.spotify
  center_tv:
    name: Center TV
    entities:
      - script.tv_center_power_up
      - script.tv_center_power_down
      - script.tv_center_volume_up
      - script.tv_center_volume_down
      - script.tv_center_volume_way_up
      - script.tv_center_volume_way_down
      - script.tv_center_mute
      - media_player.center_chromecast
      - media_player.surround_chromecast
  side_tvs:
    name: Side TVs
    entities:
      - script.tv_sides_power_up
      - script.tv_sides_power_down
      - script.tv_sides_volume_up
      - script.tv_sides_volume_down
      - script.tv_sides_volume_way_up
      - script.tv_sides_volume_way_down
      - script.tv_sides_mute
      - media_player.left_chromecast
      - media_player.right_chromecast
  garage:
    name: Garage
    entities:
      - cover.west_garage_door
      - cover.east_garage_door
      - sensor.bens_garage_door_raw
      - sensor.britts_garage_door_raw
  Weather Summary:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
  Alarms:
    entities:
      - input_boolean.alarm_lights
      - input_boolean.alarm_lights_today
      - input_number.alarm_hour
      - input_number.alarm_minute
  Automations:
    entities:
      - automation.arrive_home_living_room_lights
      - automation.ben_walkup_music
      - automation.britt_walkup_music
      - automation.disable_todays_alarm
      - automation.enable_todays_alarm
      - automation.garage_open
      - automation.no_one_home_lights_off
  Weather:
    view: yes
    entities:
      - group.weather_summary
  Admin:
    view: yes
    entities:
      - group.alarms
      - group.automations
  our_devices:
    name: Our Devices
    entities:
      - device_tracker.ben
      - device_tracker.britt