homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
    
  customize:
    light.bedroom_overhead_level_2:
      friendly_name: Bedroom Ceiling

zone:
  name: Work
  latitude: 40.813299
  longitude: -96.710486
  radius: 200
  icon: mdi:desktop-mac

zone 2:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

http:
  api_password: !secret http_password
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  server_port: 8123
  
mqtt:
#  broker: m12.cloudmqtt.com
#  port: 14782
#  username: HomeAssistant
#  password: !secret mqtt_password
  broker: 127.0.0.1
  port: 1883


device_tracker:
  platform: owntracks
  max_gps_accuracy: 200
  track_new_devices: no

# Track the sun
#sun:

sensor:
  # Prediction of weather
  - platform: yr
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
  - platform: fastdotcom
    minute:
      - 5
      - 15
      - 25
      - 35
      - 45
      - 55
  - platform: mqtt
    state_topic: "home/garage/door/c0928600"
    name: "East Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"
    value_template: '{{ value_json.Distance }}'
  - platform: mqtt
    state_topic: "home/garage/door/4413c000"
    name: "West Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"
    value_template: '{{ value_json.Distance }}'
  - platform: mqtt
    state_topic: "owntracks/Ben/g3"
    name: "Ben's Phone Battery"
    qos: 0
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend
conversation:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  username: !secret nest_user 
  password: !secret nest_password

thermostat:
  platform: nest

input_boolean:
  alarm_lights:
    name: Should Alarm Lights
    initial: on
    icon: mdi:alarm

cover:
#garage_door:
  - platform: mqtt
    name: "East Garage Door"
    state_topic: "home/garage/door/c0928600"
    command_topic: "home/garage/door/c0928600/set"
    optimistic: false
    value_template: '{{ value_json.Status }}'
    payload_open: "open"
    payload_close: "close"
#    service_open: "open"
#    service_close: "close"
    state_open: "open"
    state_closed: "closed"
  - platform: mqtt
    name: "West Garage Door"
    state_topic: "home/garage/door/4413c000"
    command_topic: "home/garage/door/4413c000/set"
    optimistic: false
    value_template: '{{ value_json.Status }}'
#    service_open: "open"
#    service_close: "close"
    payload_open: "open"
    payload_close: "close"
    state_open: "open"
    state_closed: "closed"

notify:
#  platform: html5
#  name: HTML5
#  gcm_api_key: !secret gcm_api_key
#  gcm_sender_id: !secret gcm_sender_id
  platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet



group:
#  default_view:
#    view: yes
#    entities:
#      - alarm_clock.bedroom
#      - group.bedroom
#      - thermostat.hallwaynest
#      - speedtest
#      - group.media
  bedroom_alarm_lights:
    name: Bedroom Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom_overhead_level_2
  bedroom:
    icon: mdi:hotel
    entities:
      - light.bedroom_overhead_level_2
      - input_boolean.alarm_lights
  speedtest:
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.fastcom_download
  media:
    entities:
      - media_player.center_chromecast
      - media_player.left_chromecast
      - media_player.right_chromecast
      - media_player.basement

alarm_clock:

automation:
#- alias: Leave Home
#  entity_id: device_tracker.ben_g3
#  zone: zone.home
#  event: leave
#- alias: Arrive Home
#  entity_id: device_tracker.ben_g3
#  zone: zone.home
#  event: enter
#- alias: Leave Work
#  entity_id: device_tracker.ben_g3
#  zone: zone.work
#  event: leave
#- alias: Arrive at Work
#  entity_id: device_tracker.ben_g3
#  zone: zone.work
#  event: enter

- alias: Wake Up Dim
  trigger:
    platform: time
    hours: 7
    minutes: 40
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.bedroom_alarm_lights
    data:
      brightness: 50

- alias: Wake Up Medium
  trigger:
    platform: time
    hours: 7
    minutes: 50
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.bedroom_alarm_lights
    data:
      brightness: 100

- alias: Wake Up Bright
  trigger:
    platform: time
    hours: 8
    minutes: 0
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.bedroom_alarm_lights
    data:
      brightness: 200

- alias: Wake Up Toggle
  trigger:
    platform: time
    seconds: '/5'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '8:10:00'
        before: '8:20:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.toggle
    entity_id: group.bedroom_alarm_lights

- alias: Wake Up Over
  trigger:
    platform: time
    hours: 9
    minutes: 0
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_off
    entity_id: group.bedroom_alarm_lights
#- alias: time
#  trigger:
#    platform: time
#    minutes: '/1'
#    seconds: 0
#  action:
#    - service: notify.pushbullet
#      data:
#        message: lolol
