homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 400
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
    
  customize:
    light.bedroom_overhead_level_2:
      friendly_name: Bedroom Ceiling

zone:
  name: Work
  latitude: 40.813299
  longitude: -96.710486
  radius: 500
  icon: mdi:desktop-mac

zone 2:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

http:
  api_password: !secret http_password
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  server_port: 8123
  
mqtt:
#  broker: m12.cloudmqtt.com
#  port: 14782
#  username: HomeAssistant
#  password: !secret mqtt_password
  broker: 127.0.0.1
  port: 1883


device_tracker:
  platform: owntracks
  max_gps_accuracy: 200
  track_new_devices: yes

# Track the sun
#sun:

sensor:
  # Prediction of weather
  - platform: forecast
    api_key: !secret forecast_api_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
  - platform: fastdotcom
    minute:
      - 5
      - 15
      - 25
      - 35
      - 45
      - 55
  - platform: mqtt
    state_topic: "home/garage/door/c0928600"
    name: "Britt's Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"
    value_template: '{{ value_json.Distance }}'
  - platform: mqtt
    state_topic: "home/garage/door/4413c000"
    name: "Ben's Garage Door Raw"
    qos: 0
    unit_of_measurement: "ft"
    value_template: '{{ value_json.Distance }}'
  - platform: mqtt
    state_topic: "owntracks/Ben/g3"
    name: "Ben's Phone Battery"
    qos: 0
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend
conversation:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# Checks for available updates
updater:

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  username: !secret nest_user 
  password: !secret nest_password

climate:
  platform: nest

input_boolean:
  alarm_lights:
    name: Should Alarm Lights
    initial: on
    icon: mdi:alarm

cover:
  - platform: mqtt
    name: "Britt's Garage Door"
    state_topic: "home/garage/door/c0928600"
    command_topic: "home/garage/door/c0928600/set"
    optimistic: false
    value_template: '{{ value_json.Status }}'
    payload_open: "open"
    payload_close: "close"
    state_open: "open"
    state_closed: "closed"
  - platform: mqtt
    name: "Ben's Garage Door"
    state_topic: "home/garage/door/4413c000"
    command_topic: "home/garage/door/4413c000/set"
    optimistic: false
    value_template: '{{ value_json.Status }}'
    payload_open: "open"
    payload_close: "close"
    state_open: "open"
    state_closed: "closed"

notify:
#  platform: html5
#  name: HTML5
#  gcm_api_key: !secret gcm_api_key
#  gcm_sender_id: !secret gcm_sender_id
  platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet


shell_command:
  update_hass: /home/pi/HomeAssistantConfig/update.sh
  pull_github: git -C '/home/pi/HomeAssistantConfig' pull

script:
  restart_hass:
    alias: Restart HomeAssistant
    sequence:
      - service: homeassistant.restart
  update_hass:
    alias: Update HomeAssistant
    sequence:
      - service: shell_command.update_hass
  pull_github:
    alias: Pull from Github
    sequence:
      - service: shell_command.pull_github
  reload_groups:
    alias: Reload Groups
    sequence:
      - service: group.reload
  reload_automation:
    alias: Reload Automation
    sequence:
      - service: automation.reload
        

group:
  default_view:
    view: yes
    entities:
      - updater.updater
      - sensor.bens_phone_battery
      - device_tracker.ben_g3
      - device_tracker.britt_britt
      - group.bedroom
      - group.garage
      - climate.hallwaynest
      - group.speedtest
      - group.media
  bedroom:
    icon: mdi:hotel
    entities:
      - light.bedroom_overhead_level_2
      - input_boolean.alarm_lights
  speedtest:
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.fastcom_download
  media:
    entities:
      - media_player.center_chromecast
      - media_player.left_chromecast
      - media_player.right_chromecast
      - media_player.basement
  garage:
    entities:
      - cover.bens_garage_door
      - cover.britts_garage_door
      - sensor.bens_garage_door_raw
      - sensor.britts_garage_door_raw
  Home Assistant:
    entities:
      - script.restart_hass
      - script.update_hass
      - script.pull_github
      - script.reload_automation
      - script.reload_groups
  Admin:
    view: yes
    entities:
      - group.home_assistant
  Weather:
    view: yes
    entities:
      - sensor.forecastio_apparent_temperature
      - sensor.forecastio_cloud_coverage
      - sensor.forecastio_daily_high_apparent_temperature
      - sensor.forecastio_daily_high_temperature
      - sensor.forecastio_daily_low_apparent_temperature
      - sensor.forecastio_daily_low_temperature
      - sensor.forecastio_daily_max_precip_intensity
      - sensor.forecastio_daily_summary
      - sensor.forecastio_dew_point
      - sensor.forecastio_hourly_summary
      - sensor.forecastio_humidity
      - sensor.forecastio_icon
      - sensor.forecastio_minutely_summary
      - sensor.forecastio_nearest_storm_bearing
      - sensor.forecastio_nearest_storm_distance
      - sensor.forecastio_precip
      - sensor.forecastio_precip_intensity
      - sensor.forecastio_precip_probability
      - sensor.forecastio_pressure
      - sensor.forecastio_summary
      - sensor.forecastio_temperature
      - sensor.forecastio_visibility
      - sensor.forecastio_wind_bearing
      - sensor.forecastio_wind_speed


automation:
- alias: Leave Home
  trigger:
    platform: zone
    entity_id: device_tracker.ben_g3
    zone: zone.home
    event: leave
  action:
    - service: notify.pushbullet
      data: 
        message: "Ben left home"
- alias: Arrive Home
  trigger:
    platform: zone
    entity_id: device_tracker.ben_g3
    zone: zone.home
    event: enter
  action:
    - service: notify.pushbullet
      data: 
        message: "Ben arrived home"

- alias: Britt Left Home
  trigger:
    platform: zone
    entity_id: device_tracker.britt_britt
    zone: zone.home
    event: leave
  action:
    - service: notify.pushbullet
      data:
        message: "Britt left home"
- alias: Britt Arrived Home
  trigger:
    platform: zone
    entity_id: device_tracker.britt_britt
    zone: zone.home
    event: enter
  action:
    - service: notify.pushbullet
      data:
        message: "Britt arrived home"
      
- alias: Leave Work
  trigger:
    platform: zone
    entity_id: device_tracker.ben_g3
    zone: zone.work
    event: leave
  action:
    - service: notify.pushbullet
      data: 
        message: "Ben left work"
- alias: Arrive at Work
  trigger:
    platform: zone
    entity_id: device_tracker.ben_g3
    zone: zone.work
    event: enter
  action:
    - service: notify.pushbullet
      data: 
        message: "Ben arrived at work"

- alias: Wake Up Dim
  trigger:
    platform: time
    hours: 7
    minutes: 40
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.bedroom_alarm_lights
    data:
      brightness: 50

- alias: Wake Up Medium
  trigger:
    platform: time
    hours: 7
    minutes: 50
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.bedroom_alarm_lights
    data:
      brightness: 100

- alias: Wake Up Bright
  trigger:
    platform: time
    hours: 8
    minutes: 0
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_on
    entity_id: group.bedroom_alarm_lights
    data:
      brightness: 200

- alias: Wake Up Toggle
  trigger:
    platform: time
    seconds: '/5'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '8:10:00'
        before: '8:20:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.toggle
    entity_id: group.bedroom_alarm_lights

- alias: Wake Up Over
  trigger:
    platform: time
    hours: 9
    minutes: 0
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.alarm_lights
        state: 'on'
  action:
    service: light.turn_off
    entity_id: group.bedroom_alarm_lights

- alias: Garage Open
  trigger:
    platform: state
    entity_id: cover.bens_garage_door, cover.britts_garage_door
    state: 'open'
    for:
      minutes: 1
  action:
    - service: notify.pushbullet
      data_template:
        message: '{{ trigger.to_state.attributes["friendly_name"] }} has been {{ trigger.to_state.state }} for {{ trigger.for }}'
    

#- alias: time
#  trigger:
#    platform: time
#    minutes: '/1'
#    seconds: 0
#  action:
#    - service: notify.pushbullet
#      data:
#        message: lolol
