homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 400
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize:
    light.bedroom:
      friendly_name: Bedroom
      icon: mdi:hotel
    switch.kitchen_ceiling_switch:
      friendly_name: Kitchen Ceiling
      icon: mdi:stove
    switch.living_room_switch:
      friendly_name: Living Room Lamps
      icon: mdi:readability
    sensor.dark_sky_apparent_temperature:
      friendly_name: Temp
    sensor.dark_sky_overnight_low_apparent_temperature_0d:
      friendly_name: Low Temp
    sensor.dark_sky_daytime_high_apparent_temperature_0d:
      friendly_name: High Temp
    sensor.dark_sky_precip_probability:
      friendly_name: Precip %
    sensor.dark_sky_daily_max_precip_intensity_0d:
      friendly_name: Precip Intensity
    sensor.dark_sky_summary:
      friendly_name: Now
    sensor.dark_sky_hourly_summary:
      friendly_name: Today
    sensor.dark_sky_daily_summary:
      friendly_name: This Week
    person.ben:
      entity_picture: https://secure.gravatar.com/avatar/72ad9ece205d095c1684cfd6b1b57508?s=64
    person.britt:
      entity_picture: https://lh3.googleusercontent.com/a-/AOh14Gjqj1e6mtfnZoimmBW-U75qcaNDM-8KFZ05y-KE
    cover.west_garage_door:
      device_class: garage
    cover.east_garage_door:
      device_class: garage

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: legacy_api_password
      api_password: !secret http_password
    - type: homeassistant

system_health:

mobile_app:

lovelace:
  mode: yaml

script: !include scripts.yaml

automation: !include automations.yaml

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:home

http:
  base_url: !secret base_url
  cors_allowed_origins: !secret base_url
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies: 192.168.1.20

emulated_hue:
  listen_port: 80
  exposed_domains:
    - switch
    - light
    - input_boolean
    - media_player
    - script

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include google_service_account.json
  secure_devices_pin: !secret google_assistant_secure_device_pin
  exposed_domains:
    - switch
    - light
    - input_boolean
  entity_config:
    cover.google_assistant_east_garage_door:
      name: East Garage Door
      expose: true
    cover.google_assistant_west_garage_door:
      name: West Garage Door
      expose: true


device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin
    password: !secret router_password
    new_device_defaults:
      track_new_devices: false
  - platform: google_maps
    username: origaslocationsharing@gmail.com
    max_gps_accuracy: 200

# Track the sun
#sun:

weather:
  - platform: darksky
    api_key: !secret forecast_api_key

sensor:
  - platform: uptime
    unit_of_measurement: hours
  # Prediction of weather
  - platform: darksky
    api_key: !secret forecast_api_key
    forecast:
      - 0
    monitored_conditions:
      - summary
      #- icon
      #- nearest_storm_distance
      #- nearest_storm_bearing
      #- precip_type
      - precip_intensity
      - precip_probability
      #- temperature
      - apparent_temperature
      #- dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      #- pressure
      #- visibility
      #- minutely_summary
      - hourly_summary
      - daily_summary
      #- temperature_high
      #- temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
  # - platform: speedtestdotnet
  #   monitored_conditions:
  #     - ping
  #     - download
  #     - upload
  #   scan_interval: '0:15'
  # - platform: fastdotcom
  #   scan_interval: '0:15'

# Allows you to issue voice commands from the frontend
conversation:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration panel
config:

# Discover some devices automatically
discovery:
  ignore:
    - netgear_router
    - igd

# Enables support for tracking state changes over time.
recorder:
  db_url: mysql://hass:mariapassword@core-mariadb/homeassistant?charset=utf8
  commit_interval: 60
  include:
    domains:
      - automation
      - cover
      - light
      - switch
      - input_boolean
      - climate
      - person
    entities:
      - sensor.eastgaragesensor
      - sensor.westgaragesensor
      - device_tracker.ben
      - device_tracker.britt
      - device_tracker.google_maps_104506917447049484567
      - device_tracker.google_maps_100084428449204867015
      
history:

logbook:

# Checks for available updates
updater:

zwave:
  usb_path: /dev/ttyACM0
  #config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  client_id: 0f34338b-5247-45f3-b4a0-a09da4cabba1
  client_secret: !secret nest_secret

climate:
  platform: nest

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# Proxies traffic to the actual cover, but doesn't allow open and only allows close when current state is open to avoid flipping the relay when closed, accidentally opening
cover:
  - platform: template
    covers:
      google_assistant_east_garage_door:
        friendly_name: "Google Assistant East Garage Door"
        device_class: garage
        value_template: "{{ states('cover.east_garage_door') }}"
        availability_template: >-
          {%- if not is_state("cover.east_garage_door", "unavailable") %}
            true
          {%- endif %}
        close_cover:
          - service: logbook.log
            data:
              name: Google Assistant East Garage Door
              message: is attempting to close if it's currently open
              entity_id: cover.google_assistant_east_garage_door
              domain: cover
          - condition: state
            entity_id: cover.east_garage_door
            state: "open"
          - service: logbook.log
            data:
              name: Google Assistant East Garage Door
              message: is being closed
              entity_id: cover.google_assistant_east_garage_door
              domain: cover
          - service: cover.close_cover
            data:
              entity_id: cover.east_garage_door
        open_cover:
          - service: logbook.log
            data:
              name: Google Assistant East Garage Door
              message: is attempting to open if it's currently closed
              entity_id: cover.google_assistant_east_garage_door
              domain: cover
          - condition: state
            entity_id: cover.east_garage_door
            state: "closed"
          - service: logbook.log
            data:
              name: Google Assistant East Garage Door
              message: is being opened
              entity_id: cover.google_assistant_east_garage_door
              domain: cover
          - service: cover.open_cover
            data:
              entity_id: cover.east_garage_door
      google_assistant_west_garage_door:
        friendly_name: "Google Assistant West Garage Door"
        device_class: garage
        value_template: "{{ states('cover.west_garage_door') }}"
        availability_template: >-
          {%- if not is_state("cover.west_garage_door", "unavailable") %}
            true
          {%- endif %}
        close_cover:
          - service: logbook.log
            data:
              name: Google Assistant West Garage Door
              message: is attempting to close if it's currently open
              entity_id: cover.google_assistant_west_garage_door
              domain: cover
          - condition: state
            entity_id: cover.west_garage_door
            state: "open"
          - service: logbook.log
            data:
              name: Google Assistant West Garage Door
              message: is being closed
              entity_id: cover.google_assistant_west_garage_door
              domain: cover
          - service: cover.close_cover
            data:
              entity_id: cover.west_garage_door
        open_cover:
          - service: logbook.log
            data:
              name: Google Assistant West Garage Door
              message: is attempting to open if it's currently closed
              entity_id: cover.google_assistant_west_garage_door
              domain: cover
          - condition: state
            entity_id: cover.west_garage_door
            state: "closed"
          - service: logbook.log
            data:
              name: Google Assistant West Garage Door
              message: is being opened
              entity_id: cover.google_assistant_west_garage_door
              domain: cover
          - service: cover.open_cover
            data:
              entity_id: cover.west_garage_door

input_boolean:
  alarm_lights:
    name: Should Alarm Lights
    icon: mdi:alarm-check
  alarm_lights_today:
    name: Today's Alarm
    icon: mdi:alarm-check

input_number:
  alarm_hour:
    name: Hour
    icon: mdi:timer
    min: 0
    max: 23
    step: 1
  alarm_minute:
    name: Minute
    icon: mdi:timer
    min: 0
    max: 55
    step: 5

tplink:
  discovery: true

stream:
ffmpeg:

camera:
  - platform: mjpeg
    name: Puppy Cam 1
    mjpeg_url: http://192.168.1.43/mjpeg.cgi
    still_image_url: http://192.168.1.43/image.jpg
    username: hass
    password: hasscam
  # - platform: ffmpeg
  #   input: rtsp://wyzertsp:rtsppass@192.168.1.47/live
  #   extra_arguments: -pred 1 -filter:v "crop=in_w/2:in_h/2"
  #   name: Puppy Cam 1
  - platform: generic
    name: Dining Room
    stream_source: rtsp://wyzertsp:rtsppass@192.168.1.46/live
    still_image_url: https://127.0.0.1/404.png
  - platform: generic
    name: Crate
    stream_source: rtsp://wyzertsp:rtsppass@192.168.1.47/live
    still_image_url: https://127.0.0.1/404.png
  # - platform: ffmpeg
  #   input: rtsp://wyzertsp:rtsppass@192.168.1.46/live
  #   name: Puppy Cam 1

notify:
#  platform: html5
#  name: HTML5
#  gcm_api_key: !secret gcm_api_key
#  gcm_sender_id: !secret gcm_sender_id
  platform: pushbullet
  api_key: !secret pushbullet_api_key
  name: pushbullet

group:
  lights:
    name: Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom
      - light.guest_bedroom
      - light.office
      - switch.kitchen_ceiling_switch
      - switch.living_room_switch
  bedroom_alarm_lights:
    name: Bedroom Lights
    icon: mdi:lightbulb
    entities:
      - light.bedroom
  kitchen_lights:
    name: Kitchen Lights
    icon: mdi:lightbulb
    entities:
      - switch.kitchen_ceiling_switch
  fans:
    name: Fans
    icon: mdi:fan
    entities:
      - switch.bedroom_fan
      - switch.office_fan
      - switch.guest_bedroom_fan
  speedtest:
    name: Speedtest
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
      - sensor.fastcom_download
  Weather Summary:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_overnight_low_apparent_temperature_0d
      - sensor.dark_sky_daytime_high_apparent_temperature_0d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_daily_max_precip_intensity_0d
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
  Alarms:
    entities:
      - input_boolean.alarm_lights
      - input_boolean.alarm_lights_today
      - input_number.alarm_hour
      - input_number.alarm_minute
  Automations:
    entities:
      - automation.arrive_home_living_room_lights
      - automation.ben_walkup_music
      - automation.britt_walkup_music
      - automation.disable_todays_alarm
      - automation.enable_todays_alarm
      - automation.garage_open
      - automation.garage_open_long_time
      - automation.no_one_home_lights_off
  our_devices:
    name: Our Devices
    entities:
      - person.ben
      - person.britt