title: Home
views:
  - title: Home
    cards:
      - type: glance
        entities:
          - device_tracker.ben
          - device_tracker.britt
          - climate.hallway_nest
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_daily_low_apparent_temperature
          - sensor.dark_sky_daily_high_apparent_temperature
          - sensor.dark_sky_precip_probability
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - cover.west_garage_door
              - cover.east_garage_door
          - type: sensor
            entity: sensor.britts_garage_door_raw
            height: 100
            line_width: 2
            accuracy: 200
          - type: sensor
            entity: sensor.bens_garage_door_raw
            height: 100
            line_width: 2
            accuracy: 200
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.bedroom_ceiling_level
          - switch.kitchen_ceiling_switch
          - switch.living_room_switch
      #- type: thermostat
        #entity: climate.hallway_nest
      - type: vertical-stack
        title: Speedtest
        show_header_toggle: true
        cards:
          - type: sensor
            entity: sensor.speedtest_download
            name: Download
            height: 40
            line_width: 1
            accuracy: 700
            hours_to_show: 168
          - type: sensor
            entity: sensor.speedtest_upload
            name: Upload
            height: 40
            line_width: 1
            accuracy: 700
            hours_to_show: 168
          - type: sensor
            entity: sensor.speedtest_ping
            name: Ping
            height: 40
            line_width: 1
            accuracy: 700
            hours_to_show: 168
          - type: sensor
            entity: sensor.fastcom_download
            name: Fast.com Download
            height: 40
            line_width: 1
            accuracy: 700
            hours_to_show: 168
  - title: media
    cards:
      - type: entities
        title: Center TV
        show_header_toggle: true
        entities:
          - script.tv_center_power_up
          - script.tv_center_power_down
          - script.tv_center_volume_up
          - script.tv_center_volume_down
          - script.tv_center_volume_way_up
          - script.tv_center_volume_way_down
          - script.tv_center_mute
      - type: media-control
        entity: media_player.center_chromecast
      - type: media-control
        entity: media_player.surround_chromecast
      - type: entities
        title: Side TVs
        show_header_toggle: true
        entities:
          - script.tv_sides_power_up
          - script.tv_sides_power_down
          - script.tv_sides_volume_up
          - script.tv_sides_volume_down
          - script.tv_sides_volume_way_up
          - script.tv_sides_volume_way_down
          - script.tv_sides_mute
      - type: media-control
        entity: media_player.left_chromecast
      - type: media-control
        entity: media_player.right_chromecast
      - type: media-control
        entity: media_player.basement_chromecast
      - type: media-control
        entity: media_player.spotify
  - title: Weather
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Weather Summary
        show_header_toggle: true
        entities:
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_daily_low_apparent_temperature
          - sensor.dark_sky_daily_high_apparent_temperature
          - sensor.dark_sky_precip_probability
          - sensor.dark_sky_daily_max_precip_intensity
          - sensor.dark_sky_summary
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary
  - title: Admin
    cards:
      - type: entities
        title: Alarms
        show_header_toggle: true
        entities:
          - input_boolean.alarm_lights
          - input_boolean.alarm_lights_today
          - input_number.alarm_hour
          - input_number.alarm_minute
      - type: entities
        title: Automations
        show_header_toggle: true
        entities:
          - automation.arrive_home_living_room_lights
          - automation.ben_walkup_music
          - automation.britt_walkup_music
          - automation.disable_todays_alarm
          - automation.enable_todays_alarm
          - automation.garage_open
          - automation.no_one_home_lights_off