esphomeyaml:
  name: westgaragedoor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.41
    gateway: 192.168.1.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.1.12'
  username: ''
  password: ''

# Enable logging
logger:

ota:
  password: !secret ota_password

switch:
  - platform: gpio
    id: GarageRelay1
    name: "GarageRelay1"
    pin: D1

sensor:
  - platform: ultrasonic
    id: GarageSensor1
    name: "GarageSensor1"
    trigger_pin: D3
    echo_pin: D2
    timeout_time: 100ms
    update_interval: 1s
    unit_of_measurement: "ft"
    filters:
      - multiply: 3.28
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
      - delta: 1
      - heartbeat: 60s

cover:
  - platform: template
    name: "West Garage Door"
    lambda: >-
      if(id(GarageSensor1).value <= 4) {
        return cover::COVER_OPEN;
      } else {
        return cover::COVER_CLOSED;
      }
    open_action:
      - switch.turn_on:
          id: GarageRelay1
      - delay: 200ms
      - switch.turn_off:
          id: GarageRelay1
    close_action:
      - switch.turn_on:
          id: GarageRelay1
      - delay: 200ms
      - switch.turn_off:
          id: GarageRelay1