esphome:
  name: eastgaragedoor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.42
    gateway: 192.168.1.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.1.12'
  username: !secret mqtt_user
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  password: !secret ota_password

switch:
  - platform: gpio
    id: EastGarageRelay
    name: "EastGarageRelay"
    pin: D1

sensor:
  - platform: ultrasonic
    id: EastGarageSensor
    name: "EastGarageSensor"
    trigger_pin: D3
    echo_pin: D2
    timeout: 10m
    update_interval: 1s
    unit_of_measurement: "ft"
    filters:
      - multiply: 3.28
      - filter_out: 0
      - median:
          window_size: 9
          send_every: 1
      - or:
        - delta: 0.5
        - heartbeat: 30min
  - platform: wifi_signal
    name: "East Garage Wifi"
    update_interval: 300s
  - platform: uptime
    name: East Garage Uptime
    update_interval: 300s

cover:
  - platform: template
    device_class: garage
    name: "East Garage Door"
    lambda: >-
      if(id(EastGarageSensor).state <= 3.5) {
        return cover::COVER_OPEN;
      } else {
        return cover::COVER_CLOSED;
      }
    open_action:
      - switch.turn_on:
          id: EastGarageRelay
      - delay: 200ms
      - switch.turn_off:
          id: EastGarageRelay
    close_action:
      - switch.turn_on:
          id: EastGarageRelay
      - delay: 200ms
      - switch.turn_off:
          id: EastGarageRelay